apiVersion: v1
kind: Pod
metadata:
  name: {{PODNAME}}
  annotations:
    k8s.v1.cni.cncf.io/networks: {{CNINETWORK}}, {{CNINETWORK}}
spec:
  containers:
    - name: {{PODNAME}}
      image: {{PODIMAGE}}
      ports:
        - containerPort: 80


